### ISSUE TITLE
/ecrire/?exec=auteurs

### ISSUE THREAD

**Issue by spipfactory** [cariagency/spip-makicatta#10]
On peu lire ... colonne de droite
![image](https://user-images.githubusercontent.com/54201034/63429124-8371a380-c419-11e9-9bec-6bc189aea9c0.png)

pourquoi ne pas avoir écrit comme ceci avec carrément l’icône .

Vous trouverez ici tous les auteurs du site. Leur statut est indiqué par la couleur de leur icone 
![image](https://user-images.githubusercontent.com/54201034/63429269-dfd4c300-c419-11e9-81ee-92f2a8484b3c.png) administrateur = vert 
![image](https://user-images.githubusercontent.com/54201034/63429218-c2075e00-c419-11e9-9324-4424a4724580.png)  rédacteur = jaune
icône : extérieurs, sans accès au site = bleue
icône : effacés = icone grise.

**Comment by julienmru** [comment]
C'est dans une chaîne de langue de SPIP donc un peu compliqué à modifier sans casser la traduction, et il est possible que cette section bouge un jour :)
