### ISSUE TITLE
/ecrire/?exec=article_edit&new=oui

### ISSUE THREAD

**Issue by spipfactory** [cariagency/spip-makicatta#5]
Constat 

Ajouter une image ou un document   , le texte sort de la fenêtre

![image](https://user-images.githubusercontent.com/54201034/63323558-5d1f0b80-c326-11e9-8289-c01f4a1a0e80.png)

**Comment by julienmru** [comment]
Ce genre d'élément est assez compliqué à styler en CSS, je vais réfléchir à comment faire ;)

**Comment by jpyrat** [comment]
Il faut surtout installer BigUp qui sera natif en SPIP 3.3 et qui marche parfaitement en SPIP 3.2 et ne pose pas ce problème de style.
BigUP peut même être mis en necessite de MakiCatta ;-)

**Comment by julienmru** [comment]
BigUp est désormais en dépendance de Makicatta donc problème résolu.
