### ISSUE TITLE
Bouton [Déplacer] (sur Fil d'Ariane)

### ISSUE THREAD

**Issue by jpyrat** [cariagency/spip-makicatta#6]
Bonjour,

SPIP a nativement un bouton [Déplacer] à droite de l'écran, sur la même ligne que le fil d'Ariane.
Ce bouton permet de gagner beaucoup de clics par rapport à aller modifier l’objet pour le déplacer

Je pose donc ça là histoire de ne pas l'oublier ;-)

**Comment by julienmru** [comment]
J'ai commencé à travailler dessus sur la branche `issue-6` (sur les articles pour le moment) mais y'a encore un peu de travail pour que le rendu soit conforme à AdminLTE + voir pourquoi ça passe plus en AJAX.

**Comment by julienmru** [comment]
Voilà ça commence à être pas mal.

Il y a un peu de test à faire je pense notamment pour l'avertissement quand il y a des brèves dans la rubrique. @jpyrat Si tu veux arranger le style c'est dans la fonction `makicatta_chercher_rubrique` dans `makicatta_fonctions.php`, tu verras que le gros est déjà fait :)
