### ISSUE TITLE
ecrire/?exec=configurer_identite

### ISSUE THREAD

**Issue by spipfactory** [cariagency/spip-makicatta#7]
Sue la page on a colonne de droite 

![image](https://user-images.githubusercontent.com/54201034/63422176-30442480-c40a-11e9-83ac-9ca3ef543ea9.png)

toutefois lorsqu'on clic sur plugins
la fenêtre s'ouvrant passe la colonne de droite a la suite  de la fenêtre principal 
![image](https://user-images.githubusercontent.com/54201034/63422365-81ecaf00-c40a-11e9-8c2e-f0d6547ef800.png)

**Comment by julienmru** [comment]
Je pensais retirer cette colonne de droit car on a déjà le menu sur la gauche, tu en penses quoi ?

**Comment by spipfactory** [comment]
je suis pas trop pour car des hébergés préfère passer par cette colonne
il me dise que la marche est moins haute pour l'utilisation de makicatta

de plus on retrouve facilement les plugins rajouté configurable

mais bon peut être demandé a realt ce qu'il en pense.

**Comment by julienmru** [comment]
Je comprends l'argument mais ça fait doublon. La marche est quand même assez haute avec Makicatta donc autant de pas garder de vieux squelettes dans le placard (sans mauvais jeu de mot).

**Comment by spipfactory** [comment]
tu prêche un convaincu

et de toute manière des qu'on modifie quelque chose , on se choppe le syndrome de l'oisillon

> Ce syndrome décrit la tendance naturelle des utilisateurs à adhérer au premier type d’interface expérimenté et à juger les autres en fonction de leur degré de similarité avec le premier. La conséquence est que les utilisateurs préfèrent en général les systèmes auxquels ils sont habitués et rejettent ceux qui ne leur sont pas familiers. Ce qui posent des problèmes en matière de design : les utilisateurs, habitués à un design, se sentent souvent mal à l’aise lorsqu’une nouvelle interface est mise en  place.
