### ISSUE TITLE
Ajout de plugin et menu de droite

### ISSUE THREAD

**Issue by spipfactory** [cariagency/spip-makicatta#8]
lorsqu'on rajoute des plugins, on constate que sur la colonne aucun icône n'apparais pour celui-ci

peu être proposé un icône par défaut
![image](https://user-images.githubusercontent.com/54201034/63422743-469eb000-c40b-11e9-8415-88431d510d03.png)

**Comment by julienmru** [comment]
Le mieux c'est soit de négocier avec les développeurs de plugin de rajouter l'icône dans leur plugin (cf. [Notes aux développeurs de plugins](https://contrib.spip.net/makicatta#Notes-aux-developpeurs-de-plugins)), ou de rajouter les icônes dans [makicatta_quete_icone](https://github.com/cariagency/spip-makicatta/blob/master/makicatta_fonctions.php).

Mais je vais voir pour mettre une icône générique quand même ;)

**Comment by jpyrat** [comment]
En l'état, je ne crois pas qu'on doive le faire au niveau des plugins (via le pipeline).
Soit le core de SPIP intègre le plugin comme nouvelle interface de SPIP, et modifie paquet.xml pour déclarer les icones FA.
Soit ça ne sera jamais totalement correct pour tous les plugins :(

**Comment by julienmru** [comment]
@jpyrat Il n'y a pas que les icônes du menu, même si c'est les icônes du menu le plus visible ;) D'où la pipeline qui permet de "traduire" en FontAwesome les différentes icônes utilisées par le plugin. Les plugins peuvent aussi potentiellement améliorer l'UX/UI grâce aux composants de AdminLTE si Makicatta est présent.

Je ne pense pas qu'il faille dépendre du core de SPIP pour avancer sur ce plugin.

**Comment by jpyrat** [comment]
Résolu par https://github.com/cariagency/spip-makicatta/commit/8f002460d8c0445f2e5dd45426f71befdefd4c17
